server:
  port: 9901
spring:
  application:
    name: service1

  datasource:
    driver-class-name: org.postgresql.Driver
  config:
    import: vault://
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    vault:
      uri: http://127.0.0.1:8200
      scheme: http
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: service1
        application-name-context: false
        profile-separator: ','
