server:
  port: 9901
spring:
  application:
    name: service1
  config:
    import: vault://

  datasource:
    url: jdbc:postgresql://${SPRING_POSTGRES_HOST:localhost}:${SPRING_POSTGRES_PORT:5432}/${SPRING_POSTGRES_DB:mydb}
    username: ${SPRING_POSTGRES_USERS:myuser}
    password: ${SPRING_POSTGRES_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    vault:
      uri: http://127.0.0.1:8200
      scheme: http
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: service1
        application-name-context: false
        profile-separator: ','
